# KenBuild test game
$(SRC)/bstub.$o: $(SRC)/bstub.c $(ENGINEINC)/compat.h $(ENGINEINC)/build.h $(ENGINEINC)/compat.h $(ENGINEINC)/editor.h $(ENGINEINC)/pragmas.h $(ENGINEINC)/baselayer.h $(SRC)/names.h $(ENGINEINC)/osd.h $(ENGINEINC)/cache1d.h
$(SRC)/config.$o: $(SRC)/config.c $(ENGINEINC)/build.h $(ENGINEINC)/compat.h $(SRC)/game.h $(ENGINEINC)/osd.h $(ENGINEINC)/scriptfile.h $(ENGINEINC)/winlayer.h $(ENGINEINC)/baselayer.h
$(SRC)/game.$o: $(SRC)/game.c $(ENGINEINC)/build.h $(ENGINEINC)/compat.h $(SRC)/names.h $(ENGINEINC)/pragmas.h $(ENGINEINC)/cache1d.h $(SRC)/game.h $(ENGINEINC)/osd.h $(ENGINEINC)/mmulti.h $(SRC)/kdmsound.h $(ENGINEINC)/baselayer.h
$(SRC)/kdmsound.$o: $(SRC)/kdmsound.c $(SRC)/kdmsound.h $(ENGINEINC)/compat.h $(ENGINEINC)/pragmas.h $(ENGINEINC)/cache1d.h
$(SRC)/kdmsound_sdl2.$o: $(SRC)/kdmsound_sdl2.c $(SRC)/kdmsound.h
$(SRC)/kdmsound_stub.$o: $(SRC)/kdmsound_stub.c

$(SRC)/buildres.$(res): $(SRC)/buildres.rc $(ENGINEINC)/startwin_win.rc $(ENGINEINC)/startwin_win.h $(RSRC)/startwin_build.bmp $(RSRC)/build_icon.ico $(RSRC)/build.manifest
$(SRC)/gameres.$(res): $(SRC)/gameres.rc $(ENGINEINC)/startwin_win.rc $(ENGINEINC)/startwin_win.h $(RSRC)/startwin_game.bmp $(RSRC)/game_icon.ico $(RSRC)/game.manifest

# Derived source files from art assets
$(RSRC)/build_bmp.$o: $(RSRC)/build_bmp.c
$(RSRC)/build_bmp.c: $(RSRC)/build.bmp
$(RSRC)/build_startwin_gtk_gresource.c $(RSRC)/build_startwin_gtk_gresource.h: $(RSRC)/build_startwin_gtk.gresource.xml $(RSRC)/build.png $(ENGINERSRC)/startwin_gtk.glade $(RSRC)/startwin_gtk_version.txt $(RSRC)/startwin_gtk_website.txt $(RSRC)/build_startwin_gtk_appname.txt
$(RSRC)/game_bmp.$o: $(RSRC)/game_bmp.c
$(RSRC)/game_bmp.c: $(RSRC)/game.bmp
$(RSRC)/game_startwin_gtk_gresource.c $(RSRC)/game_startwin_gtk_gresource.h: $(RSRC)/game_startwin_gtk.gresource.xml $(RSRC)/game.png $(ENGINERSRC)/startwin_gtk.glade $(RSRC)/startwin_gtk_version.txt $(RSRC)/startwin_gtk_website.txt $(RSRC)/game_startwin_gtk_appname.txt
